#!/bin/sh

# Es kann ein Argument angegeben werden, dass als Regex für grep -E über die 
# Ergebnisliste behandelt wird.

set -eu

svn status | grep -E '^---.+list.+«:$' | sed -E -e 's/^.+»//' -e 's/«:$//' |
while read line; do
    if [ $# -eq 0 ]; then
        printf "${line}\n"
        continue
    fi
    if printf "${line}" | grep -q -E "$1"; then
        printf "${line}\n"
    fi
done | sort
