#!/bin/sh

# only changelist from argument
# without header
# only those files which are not locked
# only paths/files
# lock those files

svn st --changelist "$1" \
    | tail -n +3 \
    | grep -E -i -v "^.....K" \
    | cut -c 9- \
    | xargs svn lock

